# what needs to be installed: nginx
---
- hosts: loadbalancers
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: make sure nginx is running
      # service: name=nginx state=started enabled=yes
      service:
        name: nginx
        state: started
        enabled: yes
