# what needs to be installed: nginx
---
- hosts: loadbalancers
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        status: present
        update_cache: yes

#- hosts: control
#